version: '3'

services: 
    consumer:
        image: golang:1.14-alpine
        command: go run . --topic test_topic --broker kafka:9092
        working_dir: /root/
        volumes:
        - .:/root
        depends_on:
        - kafka

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: ap_zookeeper
        ports:
        - "2181:2181"

    kafka:
        container_name: ap_kafka
        image: wurstmeister/kafka
        restart: always
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "test_topic:2:1"
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        ports:
            - "9092:9092"
            - "9094:9094"
        depends_on:
            - zookeeper