version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
    depends_on: 
      - postgres 
    environment: 
      DATABASE_HOST: postgres:5432    
    networks: 
      - backend

  postgres:
    image: postgres:latest
    container_name: user_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:    