/*
 * Shop
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"context"
	"encoding/json"
	"log"
	"net/http"

	"github.com/azomio/courses/lesson4/pkg/grpc/user"
)

func LoginUser(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	var body LoginRequest
	reader, err := r.GetBody()
	if err != nil {
		log.Fatal(err)
	}
	err = json.NewDecoder(reader).Decode(&body)
	if err != nil {
		log.Fatal(err)
	}

	req := &user.LoginRequest{
		Email: body.Email,
		Pwd:   body.Password,
	}
	resp, err := s.AuthGRPCClient.Login(context.Background(), req)
	if err != nil {
		log.Fatal(err)
	}
	respBody := LoginResponse{
		JWT: resp.Jwt,
	}
	json.NewEncoder(w).Encode(&respBody)

	w.WriteHeader(http.StatusOK)
}
