// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Movie movie
//
// swagger:model Movie
type Movie struct {

	// category
	Category int64 `json:"Category,omitempty"`

	// ID
	ID int32 `json:"ID,omitempty"`

	// release year
	ReleaseYear string `json:"ReleaseYear,omitempty"`

	// title
	Title string `json:"Title,omitempty"`
}

// Validate validates this movie
func (m *Movie) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Movie) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Movie) UnmarshalBinary(b []byte) error {
	var res Movie
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
