// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Profile profile
//
// swagger:model Profile
type Profile struct {

	// age
	Age int64 `json:"Age,omitempty"`

	// balance
	Balance float64 `json:"Balance,omitempty"`

	// display name
	DisplayName string `json:"DisplayName,omitempty"`

	// email
	Email string `json:"Email,omitempty"`

	// ID
	ID int64 `json:"ID,omitempty"`

	// phone
	Phone string `json:"Phone,omitempty"`

	// role
	Role string `json:"Role,omitempty"`

	// status
	Status int64 `json:"Status,omitempty"`
}

// Validate validates this profile
func (m *Profile) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Profile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Profile) UnmarshalBinary(b []byte) error {
	var res Profile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
