// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RentMovieResponse rent movie response
//
// swagger:model RentMovieResponse
type RentMovieResponse struct {

	// payload
	Payload *RentMovieResponsePayload `json:"Payload,omitempty"`
}

// Validate validates this rent movie response
func (m *RentMovieResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RentMovieResponse) validatePayload(formats strfmt.Registry) error {

	if swag.IsZero(m.Payload) { // not required
		return nil
	}

	if m.Payload != nil {
		if err := m.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RentMovieResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RentMovieResponse) UnmarshalBinary(b []byte) error {
	var res RentMovieResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RentMovieResponsePayload rent movie response payload
//
// swagger:model RentMovieResponsePayload
type RentMovieResponsePayload struct {

	// movie ID
	MovieID int32 `json:"MovieID,omitempty"`

	// rent end time
	RentEndTime int64 `json:"RentEndTime,omitempty"`
}

// Validate validates this rent movie response payload
func (m *RentMovieResponsePayload) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RentMovieResponsePayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RentMovieResponsePayload) UnmarshalBinary(b []byte) error {
	var res RentMovieResponsePayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
