version: '3'
services:
    graphite:
        image: graphiteapp/graphite-statsd
        ports:
        - 80:80
        - 8125:8125/udp
    movie:
        image: golang:1.14-alpine
        command: go run .
        ports:
        - 9099
        working_dir: /root/
        volumes:
        - .:/root