// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/barugoo/gb-go-microservices/course-project/gateway-user/models"
)

// GetMovieOKCode is the HTTP code returned for type GetMovieOK
const GetMovieOKCode int = 200

/*GetMovieOK Successful response

swagger:response getMovieOK
*/
type GetMovieOK struct {

	/*
	  In: Body
	*/
	Payload *models.Movie `json:"body,omitempty"`
}

// NewGetMovieOK creates GetMovieOK with default headers values
func NewGetMovieOK() *GetMovieOK {

	return &GetMovieOK{}
}

// WithPayload adds the payload to the get movie o k response
func (o *GetMovieOK) WithPayload(payload *models.Movie) *GetMovieOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get movie o k response
func (o *GetMovieOK) SetPayload(payload *models.Movie) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMovieOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
