// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// ListMoviesURL generates an URL for the list movies operation
type ListMoviesURL struct {
	Category   *int64
	Limit      int64
	Offset     *int64
	OnlyRented *bool
	YearEnd    *int64
	YearStart  *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListMoviesURL) WithBasePath(bp string) *ListMoviesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListMoviesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ListMoviesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/movies"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var categoryQ string
	if o.Category != nil {
		categoryQ = swag.FormatInt64(*o.Category)
	}
	if categoryQ != "" {
		qs.Set("category", categoryQ)
	}

	limitQ := swag.FormatInt64(o.Limit)
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	var offsetQ string
	if o.Offset != nil {
		offsetQ = swag.FormatInt64(*o.Offset)
	}
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	var onlyRentedQ string
	if o.OnlyRented != nil {
		onlyRentedQ = swag.FormatBool(*o.OnlyRented)
	}
	if onlyRentedQ != "" {
		qs.Set("only_rented", onlyRentedQ)
	}

	var yearEndQ string
	if o.YearEnd != nil {
		yearEndQ = swag.FormatInt64(*o.YearEnd)
	}
	if yearEndQ != "" {
		qs.Set("year_end", yearEndQ)
	}

	var yearStartQ string
	if o.YearStart != nil {
		yearStartQ = swag.FormatInt64(*o.YearStart)
	}
	if yearStartQ != "" {
		qs.Set("year_start", yearStartQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ListMoviesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ListMoviesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ListMoviesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ListMoviesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ListMoviesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ListMoviesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
