// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/barugoo/gb-go-microservices/course-project/gateway-user/models"
)

// ListMoviesOKCode is the HTTP code returned for type ListMoviesOK
const ListMoviesOKCode int = 200

/*ListMoviesOK Successful response

swagger:response listMoviesOK
*/
type ListMoviesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListMoviesResponse `json:"body,omitempty"`
}

// NewListMoviesOK creates ListMoviesOK with default headers values
func NewListMoviesOK() *ListMoviesOK {

	return &ListMoviesOK{}
}

// WithPayload adds the payload to the list movies o k response
func (o *ListMoviesOK) WithPayload(payload *models.ListMoviesResponse) *ListMoviesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list movies o k response
func (o *ListMoviesOK) SetPayload(payload *models.ListMoviesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMoviesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
