// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/barugoo/gb-go-microservices/course-project/gateway-user/models"
)

// RentMovieOKCode is the HTTP code returned for type RentMovieOK
const RentMovieOKCode int = 200

/*RentMovieOK Successful response

swagger:response rentMovieOK
*/
type RentMovieOK struct {

	/*
	  In: Body
	*/
	Payload *models.RentMovieResponse `json:"body,omitempty"`
}

// NewRentMovieOK creates RentMovieOK with default headers values
func NewRentMovieOK() *RentMovieOK {

	return &RentMovieOK{}
}

// WithPayload adds the payload to the rent movie o k response
func (o *RentMovieOK) WithPayload(payload *models.RentMovieResponse) *RentMovieOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rent movie o k response
func (o *RentMovieOK) SetPayload(payload *models.RentMovieResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RentMovieOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RentMovieBadRequestCode is the HTTP code returned for type RentMovieBadRequest
const RentMovieBadRequestCode int = 400

/*RentMovieBadRequest Not enough balance

swagger:response rentMovieBadRequest
*/
type RentMovieBadRequest struct {
}

// NewRentMovieBadRequest creates RentMovieBadRequest with default headers values
func NewRentMovieBadRequest() *RentMovieBadRequest {

	return &RentMovieBadRequest{}
}

// WriteResponse to the client
func (o *RentMovieBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
