CREATE TABLE IF NOT EXISTS users(
   id serial PRIMARY KEY,
   display_name VARCHAR (50) UNIQUE NOT NULL,
   password_hash VARCHAR (50) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL,
   role SMALLINT NOT NULL,
   status SMALLINT NOT NULL,
   phone_number VARCHAR (15) NOT NULL,
   birth_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);