version: '3'
services:
    movie-service:
        build:
          context: .
          dockerfile: Dockerfile
        environment: 
          DATABASE_HOST: postgres:5432 
          DATABASE_NAME: postgres 
        ports:
          - '8010:8089'
      
    # postgres:
    #     image: postgres:latest
    #     container_name: postgres
    #     environment:
    #         - POSTGRES_USER=postgres 
    #         - POSTGRES_PASSWORD=postgres
    #         - POSTGRES_DB=postgres
    #     ports:
    #         - '5432:5432'
    #     networks:
    #         - backend