// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/barugoo/gb-go-microservices/course-project/gateway-user/models"
)

// ListOrdersOKCode is the HTTP code returned for type ListOrdersOK
const ListOrdersOKCode int = 200

/*ListOrdersOK Successful response

swagger:response listOrdersOK
*/
type ListOrdersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListOrdersResponse `json:"body,omitempty"`
}

// NewListOrdersOK creates ListOrdersOK with default headers values
func NewListOrdersOK() *ListOrdersOK {

	return &ListOrdersOK{}
}

// WithPayload adds the payload to the list orders o k response
func (o *ListOrdersOK) WithPayload(payload *models.ListOrdersResponse) *ListOrdersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list orders o k response
func (o *ListOrdersOK) SetPayload(payload *models.ListOrdersResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
