version: '3'
services:
    grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    movie:
        image: golang:1.14-alpine
        command: go run .
        ports:
        - '9098:9098'
        working_dir: /root/
        volumes:
        - .:/root
    client:
        image: golang:1.14-alpine
        command: go run .
        working_dir: /root/
        volumes:
        - ./client:/root           